# ~/.config/starship.toml

add_newline = false

[cmd_duration]
min_time = 10000

[directory]
truncation_length = 3
format = ""

[aws]
success_symbol = "[aws] "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
success_symbol = "[conda] "

[git_branch]
success_symbol = "[git] "

[golang]
success_symbol = "[go] "

[hg_branch]
success_symbol = "[hg] "

[java]
success_symbol = "[java] "

[memory_usage]
disabled = true

[nodejs]
success_symbol = "⬢ "

[package]
success_symbol = "[pkg] "

[php]
success_symbol = "[php] "

[python]
success_symbol = "[py] "

[ruby]
success_symbol = "[rb] "

[rust]
success_symbol = "[rust] "
